-- ============================================================================
-- Insert Sample Data for Restaurant Management System
-- ============================================================================
-- Run this after executing database-setup.sql
-- Default passwords are BCrypt encoded
-- ============================================================================

USE restaurant_db;

-- ============================================================================
-- 1. INSERT USERS
-- ============================================================================
-- Password for all users: "password123"
-- BCrypt hash: $2a$10$YourBCryptHashHere (generated by Spring Security)
-- 
-- For testing, these are the default credentials:
-- Admin: admin / admin123
-- User: user / user123

INSERT INTO users (username, email, phone, password, role, enabled, promo_code, discount_percent, promo_expires, promo_active) VALUES
-- Admin user (password: admin123)
('admin', 'admin@restaurant.com', '+1234567890', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'ADMIN', 1, NULL, 0.00, NULL, 0),

-- Regular user (password: user123)
('user', 'user@example.com', '+1234567891', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'USER', 1, 'WELCOME10', 10.00, DATE_ADD(NOW(), INTERVAL 30 DAY), 1),

-- Manager (password: manager123)
('manager', 'manager@restaurant.com', '+1234567892', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'MANAGER', 1, NULL, 0.00, NULL, 0),

-- Kitchen staff (password: kitchen123)
('kitchen', 'kitchen@restaurant.com', '+1234567893', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'KITCHEN', 1, NULL, 0.00, NULL, 0),

-- Driver (password: driver123)
('driver', 'driver@restaurant.com', '+1234567894', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'DRIVER', 1, NULL, 0.00, NULL, 0),

-- Additional test users
('john_doe', 'john@example.com', '+1234567895', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'USER', 1, 'SAVE15', 15.00, DATE_ADD(NOW(), INTERVAL 60 DAY), 1),
('jane_smith', 'jane@example.com', '+1234567896', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu', 'USER', 1, NULL, 0.00, NULL, 0);

-- ============================================================================
-- 2. INSERT MENU ITEMS (2 per category)
-- ============================================================================

INSERT INTO menus (name, description, price, category, is_available, image_url, preparation_time, ingredients, is_vegetarian, is_vegan, is_gluten_free, is_spicy, spice_level, stock_quantity, low_stock_threshold, is_featured, discount_percentage, discounted_price) VALUES

-- Appetizers
('Spring Rolls', 'Crispy vegetable rolls with sweet chili sauce', 8.99, 'Appetizers', 1, '/images/spring-rolls.jpg', 10, 'Vegetables, Rice paper, Sweet chili sauce', 1, 1, 1, 0, 0, 50, 10, 1, 10.00, 8.09),
('Garlic Bread', 'Toasted bread with garlic butter and herbs', 6.50, 'Appetizers', 1, '/images/garlic-bread.jpg', 8, 'Bread, Garlic, Butter, Herbs', 1, 0, 0, 0, 0, 40, 10, 0, 0.00, NULL),

-- Main Course
('Grilled Salmon', 'Fresh Atlantic salmon with lemon butter sauce', 24.99, 'Main Course', 1, '/images/salmon.jpg', 20, 'Salmon, Lemon, Butter, Herbs', 0, 0, 1, 0, 0, 25, 5, 1, 15.00, 21.24),
('Chicken Curry', 'Spicy chicken curry with jasmine rice', 18.99, 'Main Course', 1, '/images/chicken-curry.jpg', 25, 'Chicken, Curry spices, Rice, Coconut milk', 0, 0, 0, 1, 3, 30, 8, 1, 10.00, 17.09),

-- Desserts
('Chocolate Lava Cake', 'Warm chocolate cake with molten center', 9.99, 'Desserts', 1, '/images/lava-cake.jpg', 15, 'Chocolate, Eggs, Flour, Sugar', 1, 0, 0, 0, 0, 20, 5, 1, 0.00, NULL),
('Tiramisu', 'Classic Italian coffee-flavored dessert', 8.50, 'Desserts', 1, '/images/tiramisu.jpg', 10, 'Mascarpone, Coffee, Ladyfingers, Cocoa', 1, 0, 0, 0, 0, 18, 5, 0, 0.00, NULL),

-- Beverages
('Fresh Orange Juice', 'Freshly squeezed orange juice', 5.50, 'Beverages', 1, '/images/orange-juice.jpg', 3, 'Fresh oranges', 1, 1, 1, 0, 0, 60, 15, 0, 0.00, NULL),
('Iced Coffee', 'Cold brew coffee with ice and milk', 6.00, 'Beverages', 1, '/images/iced-coffee.jpg', 5, 'Coffee, Milk, Ice, Sugar', 1, 0, 1, 0, 0, 45, 12, 0, 5.00, 5.70),

-- Salads
('Caesar Salad', 'Romaine lettuce with Caesar dressing and croutons', 12.99, 'Salads', 1, '/images/caesar-salad.jpg', 10, 'Romaine, Caesar dressing, Croutons, Parmesan', 1, 0, 0, 0, 0, 35, 10, 0, 0.00, NULL),
('Greek Salad', 'Fresh vegetables with feta cheese and olives', 11.50, 'Salads', 1, '/images/greek-salad.jpg', 8, 'Tomatoes, Cucumber, Feta, Olives, Onions', 1, 0, 1, 0, 0, 32, 10, 0, 0.00, NULL),

-- Pasta
('Spaghetti Carbonara', 'Classic Italian pasta with bacon and cream', 16.99, 'Pasta', 1, '/images/carbonara.jpg', 18, 'Spaghetti, Bacon, Eggs, Cream, Parmesan', 0, 0, 0, 0, 0, 28, 8, 1, 10.00, 15.29),
('Penne Arrabbiata', 'Spicy tomato sauce with penne pasta', 14.50, 'Pasta', 1, '/images/arrabbiata.jpg', 15, 'Penne, Tomatoes, Garlic, Chili, Olive oil', 1, 1, 1, 1, 2, 30, 8, 0, 0.00, NULL),

-- Pizza
('Margherita Pizza', 'Classic pizza with tomato, mozzarella, and basil', 15.99, 'Pizza', 1, '/images/margherita.jpg', 20, 'Dough, Tomato sauce, Mozzarella, Basil', 1, 0, 0, 0, 0, 22, 5, 1, 15.00, 13.59),
('Pepperoni Pizza', 'Traditional pepperoni pizza with extra cheese', 17.99, 'Pizza', 1, '/images/pepperoni.jpg', 20, 'Dough, Tomato sauce, Mozzarella, Pepperoni', 0, 0, 0, 0, 0, 25, 6, 0, 0.00, NULL),

-- Burgers
('Classic Burger', 'Beef patty with lettuce, tomato, and special sauce', 13.99, 'Burgers', 1, '/images/classic-burger.jpg', 15, 'Beef, Bun, Lettuce, Tomato, Sauce', 0, 0, 0, 0, 0, 40, 10, 0, 0.00, NULL),
('Veggie Burger', 'Plant-based patty with avocado and veggies', 12.50, 'Burgers', 1, '/images/veggie-burger.jpg', 12, 'Plant patty, Bun, Avocado, Vegetables', 1, 1, 0, 0, 0, 35, 10, 0, 5.00, 11.88),

-- Seafood
('Fish and Chips', 'Beer-battered fish with crispy fries', 19.99, 'Seafood', 1, '/images/fish-chips.jpg', 18, 'White fish, Batter, Potatoes', 0, 0, 0, 0, 0, 20, 5, 0, 0.00, NULL),
('Shrimp Scampi', 'Garlic butter shrimp with pasta', 22.50, 'Seafood', 1, '/images/shrimp-scampi.jpg', 16, 'Shrimp, Garlic, Butter, Pasta, White wine', 0, 0, 0, 0, 0, 18, 5, 1, 10.00, 20.25),

-- Soups
('Tomato Soup', 'Creamy tomato soup with basil', 7.50, 'Soups', 1, '/images/tomato-soup.jpg', 12, 'Tomatoes, Cream, Basil, Garlic', 1, 0, 1, 0, 0, 38, 10, 0, 0.00, NULL),
('Chicken Noodle Soup', 'Homemade chicken soup with egg noodles', 8.99, 'Soups', 1, '/images/chicken-soup.jpg', 15, 'Chicken, Noodles, Vegetables, Broth', 0, 0, 0, 0, 0, 42, 12, 0, 0.00, NULL),

-- Sides
('French Fries', 'Crispy golden fries with sea salt', 4.50, 'Sides', 1, '/images/fries.jpg', 8, 'Potatoes, Salt, Oil', 1, 1, 1, 0, 0, 65, 20, 0, 0.00, NULL),
('Onion Rings', 'Crispy battered onion rings', 5.50, 'Sides', 1, '/images/onion-rings.jpg', 10, 'Onions, Batter, Oil', 1, 0, 0, 0, 0, 48, 15, 0, 0.00, NULL),

-- Breakfast
('Pancakes', 'Fluffy pancakes with maple syrup and butter', 10.99, 'Breakfast', 1, '/images/pancakes.jpg', 12, 'Flour, Eggs, Milk, Maple syrup, Butter', 1, 0, 0, 0, 0, 30, 10, 0, 0.00, NULL),
('Eggs Benedict', 'Poached eggs on English muffin with hollandaise', 13.50, 'Breakfast', 1, '/images/eggs-benedict.jpg', 15, 'Eggs, English muffin, Ham, Hollandaise sauce', 0, 0, 0, 0, 0, 25, 8, 1, 10.00, 12.15),

-- Sandwiches
('Club Sandwich', 'Triple-decker with turkey, bacon, and veggies', 11.99, 'Sandwiches', 1, '/images/club-sandwich.jpg', 10, 'Turkey, Bacon, Bread, Lettuce, Tomato', 0, 0, 0, 0, 0, 28, 8, 0, 0.00, NULL),
('Grilled Cheese', 'Classic grilled cheese with cheddar', 8.50, 'Sandwiches', 1, '/images/grilled-cheese.jpg', 8, 'Bread, Cheddar cheese, Butter', 1, 0, 0, 0, 0, 35, 10, 0, 0.00, NULL);

-- ============================================================================
-- 3. INSERT DRIVERS
-- ============================================================================

INSERT INTO drivers (user_id, name, phone, email, vehicle_type, vehicle_number, license_number, available, rating, total_deliveries) VALUES
(5, 'Mike Driver', '+1234567894', 'driver@restaurant.com', 'Motorcycle', 'ABC-1234', 'DL-12345', 1, 4.85, 156),
(5, 'Sarah Delivery', '+1555123456', 'sarah@restaurant.com', 'Car', 'XYZ-5678', 'DL-67890', 1, 4.92, 203);

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check inserted data
SELECT 'Users Count:' as Info, COUNT(*) as Count FROM users
UNION ALL
SELECT 'Menu Items Count:', COUNT(*) FROM menus
UNION ALL
SELECT 'Drivers Count:', COUNT(*) FROM drivers;

-- Show all users with roles
SELECT id, username, email, role, enabled, promo_code, discount_percent 
FROM users 
ORDER BY role, username;

-- Show all menu items by category
SELECT category, COUNT(*) as items, 
       SUM(CASE WHEN is_featured = 1 THEN 1 ELSE 0 END) as featured_items,
       ROUND(AVG(price), 2) as avg_price
FROM menus 
GROUP BY category
ORDER BY category;

-- ============================================================================
-- PASSWORD REFERENCE
-- ============================================================================
-- All passwords are: admin123, user123, manager123, kitchen123, driver123
-- BCrypt hash used: $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhCu
-- This is a pre-generated hash that works for testing purposes
-- ============================================================================
